services:
  frontend:
    build:
      context: ./frontend-app
      args:
        VITE_API_URL: http://localhost:3000
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend-app
    ports:
      - "3000:3000"
    volumes:
      - backend_data:/app/data

volumes:
  backend_data: